# Generated by Django 5.1.5 on 2025-01-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
